### ISSUE TITLE
Get Data History

### ISSUE THREAD

**Issue by duff2013** [dieselrabbit/screenlogicpy#21]
I was wondering if there is a function to get the data history form the pool controller? I know the Screenlogic app can and I see some javascript projects that claim they can too.

**Comment by dieselrabbit** [comment]
While the protocol documentation describes a way to request historical data, this project does not implement it. 

screenlogicpy's primary goal was to be an API for a Home Assistant integration. Since Home Assistant has built-in functionality to record data over time and display it, the historical data requests to the ScreenLogic protocol adapter were not a target for implementation.

That doesn't mean I will _never_ add that functionality or I won't accept someone's PR to add it in a way that makes sense, it's just not thought about as a planned feature currently.
